imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
fos_user:
    from_email:
        address:        sistema@konstruye.pe
        sender_name:    Konstruye
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    registration:
            confirmation:
                    enabled: true
            form:
                type: AppBundle\Form\Type\RegistrationType
    profile:
           form:
               type: AppBundle\Form\Type\ProfileType
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
            negocio_logo:
                uri_prefix:         /images/negocios/logo
                upload_destination: %kernel.root_dir%/../web/images/negocios/logo
                namer:              vich_uploader.namer_uniqid
            servicio_foto:
                uri_prefix:         /images/servicios
                upload_destination: %kernel.root_dir%/../web/images/servicios
                namer:              vich_uploader.namer_uniqid
            negocio_foto:
                uri_prefix:         /images/negocios/fotos
                upload_destination: %kernel.root_dir%/../web/images/negocios/fotos
                namer:              vich_uploader.namer_uniqid
            negocio_anunciante:
                uri_prefix:         /images/negocios/anunciantes
                upload_destination: %kernel.root_dir%/../web/images/negocios/anunciantes
                namer:              vich_uploader.namer_uniqid
            negocio_banner_listado:
                uri_prefix:         /images/negocios/banner
                upload_destination: %kernel.root_dir%/../web/images/negocios/banner
                namer:              vich_uploader.namer_uniqid
            proyecto_foto:
                uri_prefix:         /images/negocios/proyectos/fotos
                upload_destination: %kernel.root_dir%/../web/images/negocios/proyectos/fotos
                namer:              vich_uploader.namer_uniqid
            proyecto_mini:
                uri_prefix:         /images/negocios/proyectos/mini
                upload_destination: %kernel.root_dir%/../web/images/negocios/proyectos/mini
                namer:              vich_uploader.namer_uniqid
            producto_foto_descatada:
                uri_prefix:         /images/negocios/productos/destacadas
                upload_destination: %kernel.root_dir%/../web/images/negocios/productos/destacadas
                namer:              vich_uploader.namer_uniqid
            producto_foto_galeria:
                uri_prefix:         /images/negocios/productos/galerias
                upload_destination: %kernel.root_dir%/../web/images/negocios/productos/galerias
                namer:              vich_uploader.namer_uniqid
            user_foto:
                uri_prefix:         /images/users
                upload_destination: %kernel.root_dir%/../web/images/users
                namer:              vich_uploader.namer_uniqid
knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:foundation_v5_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    connect:
        account_connector: my_user_provider
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
    resource_owners:
            facebook:
                type:          facebook
                client_id:     1586864594952225
                client_secret: e44573ce1ce0cb853e6e5021ec9cd436
                scope:         "email"
                infos_url:     "https://graph.facebook.com/me?fields=id,name,first_name,last_name,email,picture.type(normal)"
                paths:
                  profilepicture: picture.data.url
                #options:
                #    display: popup #dialog is optimized for popup window

white_october_breadcrumbs:
  separator:          ''