app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index}
lisdato_seccion:
    path:      /{slug_seccion}/{page}
    defaults:  { _controller: AppBundle:Negocio:listadoSeccion,page:1}
    requirements:
          slug_seccion: constructoras-e-inmobiliarias|compra-venta-y-alquiler-inmuebles|especialistas-servicios-personales|proveedores
          page:  \d+
buscar_negocios_by_seccion:
     path:      /buscar-negocios/{slug_seccion}
     defaults:  { _controller: AppBundle:Negocio:buscarListaNegocios,slug_seccion:null}
buscar_negocios_by_seccion_null:
     path:      /buscar-negocios/
     defaults:  { _controller: AppBundle:Negocio:buscarListaNegocios,slug_seccion:null}

buscar_productos:
     path:      /buscar-productos/
     defaults:  { _controller: AppBundle:Producto:buscarListaProductos}
show_negocio:
    #path:      /{slug_seccion}/{slug_negocio}
    path:      /negocio/{slug_negocio}
    defaults:  { _controller: AppBundle:Negocio:showDetail}
    #requirements:
          #slug_seccion: constructoras-e-inmobiliarias|compra-venta-y-alquiler-inmuebles|especialistas-servicios-personales|proveedores
search_global_negocios:
    path:      /resultado-busqueda/negocios/{search}/{page}
    defaults:  { _controller: AppBundle:Negocio:searchNegocio,search:null,page:1}

search_global_productos:
    path:      /resultado-busqueda/productos/{search}/{page}
    defaults:  { _controller: AppBundle:Producto:searchProducto,search:null,page:1}
show_producto:
    path:      /producto/{slug_producto}
    defaults:  { _controller: AppBundle:Producto:showDetail}
show_fotos_proyecto:
    path:      /proyecto/{id}
    defaults:  { _controller: AppBundle:Foto:showProyectoFotos}
ver_mas_productos_proveedor:
    path:      /ver-mas/{slug_negocio}/{page}
    defaults:  { _controller: AppBundle:Producto:showProductosProveedor,page:1}
show_contacto:
    path:      /contacto
    defaults:  { _controller: AppBundle:Default:contacto}
lisdato_seccion_categoria:
    path:      /{slug_seccion}/categoria/{slug_categoria}/{page}
    defaults:  { _controller: AppBundle:Negocio:listadoSeccionCategoria,page:1}
    requirements:
          slug_seccion: constructoras-e-inmobiliarias|compra-venta-y-alquiler-inmuebles|especialistas-servicios-personales|proveedores
          page:  \d+
show_profile_comments:
    path:      /profile/comments
    defaults:  { _controller: AppBundle:User:userCommentsShow}
negocio_proveedor_register:
    path:      /profile/proveedor/register
    defaults:  { _controller: AppBundle:Proveedor:register}
negocio_especialista_register:
    path:      /profile/proveedor/register
    defaults:  { _controller: AppBundle:Proveedor:register}
negocio_inmueble_register:
    path:      /profile/proveedor/register
    defaults:  { _controller: AppBundle:Proveedor:register}
negocio_constructura_register:
    path:      /profile/proveedor/register
    defaults:  { _controller: AppBundle:Proveedor:register}
negocio_register_confirmation:
    path:      /profile/negocio/register/confirmation
    defaults:  { _controller: AppBundle:Proveedor:registerConfirmation}

negocio_me_comentar_new:
    path:      /user-action/negocio/{slug_negocio}/comentar/new
    defaults:  { _controller: AppBundle:ComentarioNegocio:comentarNegocioUserNew}

negocio_me_comentar_edit:
    path:      /user-action/negocio/{slug_negocio}/comentar/edit
    defaults:  { _controller: AppBundle:ComentarioNegocio:comentarNegocioUserEdit}
profile_negocio_comentar_edit:
    path:      /profile/negocio/{slug_negocio}/comentar/edit
    defaults:  { _controller: AppBundle:User:userCommentEdit}
producto_me_comentar_new:
    path:      /user-action/producto/{slug_producto}/comentar/new
    defaults:  { _controller: AppBundle:ComentarioProducto:comentarProductoUserNew}
producto_me_comentar_edit:
    path:      /user-action/producto/{slug_producto}/comentar/edit
    defaults:  { _controller: AppBundle:ComentarioProducto:comentarProductoUserEdit}