app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index}
lisdato_seccion:
    path:      /{slug_seccion}/{page}
    defaults:  { _controller: AppBundle:Negocio:listadoSeccion,page:1}
    requirements:
          slug_seccion: constructoras-e-inmobiliarias|compra-venta-y-alquiler-inmuebles|especialistas-servicios-personales|proveedores
          page:  \d+
buscar_negocios_by_seccion:
     path:      /buscar-negocios/{slug_seccion}
     defaults:  { _controller: AppBundle:Negocio:buscarListaNegocios,slug_seccion:null}
buscar_negocios_by_seccion_null:
     path:      /buscar-negocios/
     defaults:  { _controller: AppBundle:Negocio:buscarListaNegocios,slug_seccion:null}

buscar_productos:
     path:      /buscar-productos/
     defaults:  { _controller: AppBundle:Producto:buscarListaProductos}
show_negocio:
    path:      /{slug_seccion}/{slug_negocio}
    defaults:  { _controller: AppBundle:Negocio:showDetail}
    requirements:
          slug_seccion: constructoras-e-inmobiliarias|compra-venta-y-alquiler-inmuebles|especialistas-servicios-personales|proveedores
search_global_negocios:
    path:      /resultado-busqueda/negocios/{search}/{page}
    defaults:  { _controller: AppBundle:Negocio:searchNegocio,search:null,page:1}

search_global_productos:
    path:      /resultado-busqueda/productos/{search}/{page}
    defaults:  { _controller: AppBundle:Producto:searchProducto,search:null,page:1}
show_producto:
    path:      /producto/{slug_producto}
    defaults:  { _controller: AppBundle:Producto:showDetail}
show_fotos_proyecto:
    path:      /proyecto/{id}
    defaults:  { _controller: AppBundle:Foto:showProyectoFotos}
ver_mas_productos_proveedor:
    path:      /ver-mas/{slug_negocio}/{page}
    defaults:  { _controller: AppBundle:Producto:showProductosProveedor,page:1}