app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#HWIOAuthBundle routes
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /secured/connect

facebook_login:
    path: /secured/login_facebook
homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index}
lisdato_seccion:
    path:      /{slug_seccion}/{page}
    defaults:  { _controller: AppBundle:Negocio:listadoSeccion,page:1}
    requirements:
          slug_seccion: constructoras-e-inmobiliarias|compra-venta-y-alquiler-inmuebles|especialistas-servicios-personales|proveedores
          page:  \d+
buscar_negocios_by_seccion:
     path:      /buscar-negocios/{slug_seccion}
     defaults:  { _controller: AppBundle:Negocio:buscarListaNegocios,slug_seccion:null}
buscar_negocios_by_seccion_null:
     path:      /buscar-negocios/
     defaults:  { _controller: AppBundle:Negocio:buscarListaNegocios,slug_seccion:null}

buscar_productos:
     path:      /buscar-productos/
     defaults:  { _controller: AppBundle:Producto:buscarListaProductos}
show_negocio:
    #path:      /{slug_seccion}/{slug_negocio}
    path:      /negocio/{slug_negocio}
    defaults:  { _controller: AppBundle:Negocio:showDetail}
    #requirements:
          #slug_seccion: constructoras-e-inmobiliarias|compra-venta-y-alquiler-inmuebles|especialistas-servicios-personales|proveedores
search_global_negocios:
    path:      /resultado-busqueda/negocios/{search}/{page}
    defaults:  { _controller: AppBundle:Negocio:searchNegocio,search:null,page:1}

search_global_productos:
    path:      /resultado-busqueda/productos/{search}/{page}
    defaults:  { _controller: AppBundle:Producto:searchProducto,search:null,page:1}
show_producto:
    path:      /producto/{slug_producto}
    defaults:  { _controller: AppBundle:Producto:showDetail}
show_fotos_proyecto:
    path:      /proyecto/{id}
    defaults:  { _controller: AppBundle:Foto:showProyectoFotos}
ver_mas_productos_proveedor:
    path:      /ver-mas/{slug_negocio}/{page}
    defaults:  { _controller: AppBundle:Producto:showProductosProveedor,page:1}
show_contacto:
    path:      /contacto
    defaults:  { _controller: AppBundle:Default:contacto}
show_faq:
    path:      /faq
    defaults:  { _controller: AppBundle:Default:faq}
lisdato_seccion_categoria:
    path:      /{slug_seccion}/categoria/{slug_categoria}/{page}
    defaults:  { _controller: AppBundle:Negocio:listadoSeccionCategoria,page:1}
    requirements:
          slug_seccion: constructoras-e-inmobiliarias|compra-venta-y-alquiler-inmuebles|especialistas-servicios-personales|proveedores
          page:  \d+
show_profile_comments:
    path:      /profile/comments
    defaults:  { _controller: AppBundle:User:userCommentsShow}

show_profile_negocios:
    path:      /profile/mis-negocios
    defaults:  { _controller: AppBundle:User:showNegociosUser}
show_profile_settings:
    path:      /profile/settings
    defaults:  { _controller: AppBundle:User:showUserSettings}
negocio_proveedor_register:
    path:      /profile/proveedor/register
    defaults:  { _controller: AppBundle:Proveedor:register}
negocio_especialista_register:
    path:      /profile/especialista/register
    defaults:  { _controller: AppBundle:Especialista:register}
negocio_inmueble_register:
    path:      /profile/inmueble/register
    defaults:  { _controller: AppBundle:Inmueble:register}
negocio_constructura_register:
    path:      /profile/constructura/register
    defaults:  { _controller: AppBundle:ConstructoraInmobiliaria:register}
negocio_register_confirmation:
    path:      /profile/negocio/register/confirmation
    defaults:  { _controller: AppBundle:Negocio:registerConfirmation}

negocio_me_comentar_new:
    path:      /user-action/negocio/{slug_negocio}/comentar/new
    defaults:  { _controller: AppBundle:ComentarioNegocio:comentarNegocioUserNew}

negocio_me_comentar_edit:
    path:      /user-action/negocio/{slug_negocio}/comentar/edit
    defaults:  { _controller: AppBundle:ComentarioNegocio:comentarNegocioUserEdit}
negocio_me_comentar_profile_edit:
    path:      /profile/negocio/{slug_negocio}/comentar/edit
    defaults:  { _controller: AppBundle:User:comentarNegocioUserEdit}
profile_negocio_comentar_edit:
    path:      /profile/negocio/{slug_negocio}/comentar/edit
    defaults:  { _controller: AppBundle:User:userCommentEdit}
producto_me_comentar_new:
    path:      /user-action/producto/{slug_producto}/comentar/new
    defaults:  { _controller: AppBundle:ComentarioProducto:comentarProductoUserNew}
producto_me_comentar_edit:
    path:      /user-action/producto/{slug_producto}/comentar/edit
    defaults:  { _controller: AppBundle:ComentarioProducto:comentarProductoUserEdit}
negocio_solicitar_cotizacion:
    path:      /user-action/negocio/{slug_negocio}/cotizacion
    defaults:  { _controller: AppBundle:Negocio:contizacion}
producto_solicitar_cotizacion:
    path:      /user-action/producto/{slug_producto}/cotizacion
    defaults:  { _controller: AppBundle:Producto:contizacion}
show_ubicaciones_buscador:
    path:      /recuperar-ubicaciones
    defaults:  { _controller: AppBundle:Default:ubicaciones}
profile_negocios_seletion:
    path: /profile/negocios/selection
    defaults:  { _controller: AppBundle:User:createNegociosUser}
profile_negocios_panel:
    path: /profile/panel/{slug_negocio}
    defaults:  { _controller: AppBundle:Panel:setPanelNegocio,slug_negocio:null}
profile_negocios_panel_dashboard:
    path: /profile/panel/auth/dashboard
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserDashbord}
profile_negocios_panel_gestion_negocio_cambiar_datos:
    path: /profile/panel/auth/datos
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserDatos}
profile_negocios_panel_gestion_negocio_cambiar_banner:
    path: /profile/panel/auth/banner
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserBanner}
profile_negocios_panel_gestion_negocio_cambiar_fotos:
    path: /profile/panel/auth/fotos
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserFotos}
profile_negocios_panel_gestion_negocio_delete_foto:
    path: /profile/panel/auth/foto/delete/{id}
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserFotoDelete}
profile_negocios_panel_gestion_negocio_list_fotos:
    path: /profile/panel/auth/list/fotos
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserListFotos}
profile_negocios_panel_gestion_negocio_cambiar_mapa:
    path: /profile/panel/auth/mapa
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserMapa}
profile_negocios_panel_gestion_negocio_cambiar_logo:
    path: /profile/panel/auth/logo
    defaults:  { _controller: AppBundle:Logo:showPanelNegocioUserLogo}
profile_negocios_panel_gestion_negocio_cambiar_anunciante:
    path: /profile/panel/auth/anunciante
    defaults:  { _controller: AppBundle:Anunciante:showPanelNegocioUserAnunciante}
profile_negocios_panel_gestion_negocio_ver_inmuebles:
    path: /profile/panel/auth/inmuebles
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserInmuebles}
profile_negocios_panel_gestion_negocio_add_inmueble:
    path: /profile/panel/auth/inmueble/add
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserInmuebleAdd}
profile_negocios_panel_gestion_negocio_edit_inmueble:
    path: /profile/panel/auth/inmueble/{id}/edit
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserInmuebleEdit}
profile_negocios_panel_gestion_negocio_delete_inmueble:
    path: /profile/panel/auth/inmueble/{id}/delete
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserInmuebleDelete}
profile_negocios_panel_gestion_negocio_sort:
    path: /profile/panel/auth/sort
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserSort}
profile_negocios_panel_gestion_negocio_ver_inmuebles_servicios:
    path: /profile/panel/auth/inmuebles/servicios
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserInmuebleServicios}
profile_negocios_panel_gestion_negocio_ver_inmuebles_servicio_add:
    path: /profile/panel/auth/inmueble/servicio/add
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserInmuebleServicioAdd}
profile_negocios_panel_gestion_negocio_ver_inmuebles_servicio_delete:
    path: /profile/panel/auth/inmueble/servicio/{id}/delete
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserInmuebleServicioDelete}
profile_negocios_panel_gestion_negocio_ver_proyectos:
    path: /profile/panel/auth/proyectos
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserProyectos}
profile_negocios_panel_gestion_negocio_list_proyectos:
    path: /profile/panel/auth/list/proyectos
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserListProyectos}
profile_negocios_panel_gestion_negocio_add_proyecto:
    path: /profile/panel/auth/proyectos/add
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserProyectoAdd}
profile_negocios_panel_gestion_negocio_edit_proyecto:
    path: /profile/panel/auth/proyecto/{id}/edit
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserProyectoEdit}
profile_negocios_panel_gestion_negocio_delete_proyecto:
    path: /profile/panel/auth/proyectos/{id}/delete
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserProyectoDelete}
profile_negocios_panel_gestion_negocio_edit_proyecto_fotos:
    path: /profile/panel/auth/proyecto/{id}/fotos
    defaults:  { _controller: AppBundle:Panel:showPanelNegocioUserProyectoFotosEdit}
