# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
  my_user_provider.class: AppBundle\Entity\FOSUBUserProvider
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.form.registration:
          class: AppBundle\Form\Type\RegistrationType
          tags:
              - { name: form.type, alias: app_user_registration }
  app.user.profile:
          class: AppBundle\Form\Type\ProfileType
          tags:
              - { name: form.type, alias: app_user_profile }

  authentication_handler:
      class:        MyUserBundle\Handler\AuthenticationHandler
      arguments:    [@router, @security.context, @fos_user.user_manager, @service_container]

  form_serializer:
    class:        AppBundle\Form\FormErrorsSerializer

  swiftmailer.command.spool_send:
      class: Symfony\Bundle\SwiftmailerBundle\Command\SendEmailCommand
      calls:
          - [ setContainer, ["@service_container"] ]
  my_user_provider:
    class: "%my_user_provider.class%"
    arguments: [@fos_user.user_manager,{facebook: facebook_id}]